controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_article_pdf:
    path: '/article/{id}/pdf'

    controller: 'App\Controller\ArticleController::generatePdf'
